In [ ]:
import cv2
import numpy as np

In [ ]:
!pip install gtts
!pip install ipython
!pip install pydub

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.4 MB/s eta 0:00:00


In [ ]:
from google.colab.patches import cv2_imshow

def enhance_shadows(image):
    # Convert the image to LAB color space
    lab_image = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)

    # Split the LAB image into channels
    l_channel, a_channel, b_channel = cv2.split(lab_image)

    # Apply CLAHE to the L channel (lightness)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_l_channel = clahe.apply(l_channel)

    # Merge the enhanced L channel with the original A and B channels
    enhanced_lab_image = cv2.merge([enhanced_l_channel, a_channel, b_channel])

    # Convert the enhanced LAB image back to BGR color space
    enhanced_image = cv2.cvtColor(enhanced_lab_image, cv2.COLOR_LAB2BGR)

    return enhanced_image

def detect_braille_character(matrix):
    # Define the Braille alphabet mapping
    braille_alphabet = {
        (1, 0, 0, 0, 0, 0): 'A',
        (1, 0, 1, 0, 0, 0): 'B',
        (1, 1, 0, 0, 0, 0): 'C',
        (1, 1, 0, 1, 0, 0): 'D',
        (1, 0, 0, 1, 0, 0): 'E',
        (1, 1, 1, 0, 0, 0): 'F',
        (1, 1, 1, 1, 0, 0): 'G',
        (1, 0, 1, 1, 0, 0): 'H',
        (0, 1, 1, 0, 0, 0): 'I',
        (0, 1, 1, 1, 0, 0): 'J',
        (1, 0, 0, 0, 1, 0): 'K',
        (1, 0, 1, 0, 1, 0): 'L',
        (1, 1, 0, 0, 1, 0): 'M',
        (1, 1, 0, 1, 1, 0): 'N',
        (1, 0, 0, 1, 1, 0): 'O',
        (1, 1, 1, 0, 1, 0): 'P',
        (1, 1, 1, 1, 1, 0): 'Q',
        (1, 0, 1, 1, 1, 0): 'R',
        (0, 1, 1, 0, 1, 0): 'S',
        (0, 1, 1, 1, 1, 0): 'T',
        (1, 0, 0, 0, 1, 1): 'U',
        (1, 0, 1, 0, 1, 1): 'V',
        (0, 1, 1, 1, 0, 1): 'W',
        (1, 1, 0, 0, 1, 1): 'X',
        (1, 1, 0, 1, 1, 1): 'Y',
        (1, 0, 0, 1, 1, 1): 'Z',
        # Add more mappings as needed
    }

    # Define the Braille number mapping
    braille_numbers = {
        (0, 0, 1, 1, 1, 0): '0',
        (1, 0, 0, 0, 0, 0): '1',
        (1, 0, 1, 0, 0, 0): '2',
        (1, 1, 0, 0, 0, 0): '3',
        (1, 0, 0, 1, 0, 0): '4',
        (1, 1, 0, 1, 0, 0): '5',
        (1, 1, 0, 1, 1, 0): '6',
        (1, 1, 0, 0, 1, 0): '7',
        (0, 1, 0, 1, 0, 0): '8',
        (0, 1, 0, 1, 1, 0): '9',
    }

    # Convert the matrix to a tuple of 1s and 0s
    dot_pattern = tuple(matrix.flatten().tolist())

    # Check if the dot pattern is in the Braille alphabet mapping
    if dot_pattern in braille_alphabet:
        return braille_alphabet[dot_pattern], 'letter'
    elif dot_pattern in braille_numbers:
        return braille_numbers[dot_pattern], 'number'
    else:
        return '?', 'unknown'

# Load the image using OpenCV
image_path = '/content/braille_F.png'  # Replace with the actual path
image = cv2.imread(image_path)
matrices = [
    np.array([[1, 0], [0, 0], [0, 0]]),
    np.array([[1, 0], [1, 0], [0, 0]]),
    np.array([[1, 1], [0, 0], [0, 0]]),
    np.array([[1, 1], [0, 1], [0, 0]]),
    np.array([[1, 0], [0, 1], [0, 0]]),
    np.array([[1, 1], [1, 0], [0, 0]]),
    np.array([[1, 1], [1, 1], [0, 0]]),
    np.array([[1, 0], [1, 1], [0, 0]]),
    np.array([[0, 1], [1, 0], [0, 0]]),
    np.array([[0, 1], [1, 1], [0, 0]]),
    np.array([[1, 0], [0, 0], [1, 0]]),
    np.array([[1, 0], [1, 0], [1, 0]]),
    np.array([[1, 1], [0, 0], [1, 0]]),
    np.array([[1, 1], [0, 1], [1, 0]]),
    np.array([[1, 0], [0, 1], [1, 0]]),
    np.array([[1, 1], [1, 0], [1, 0]]),
    np.array([[1, 1], [1, 1], [1, 0]]),
    np.array([[1, 0], [1, 1], [1, 0]]),
    np.array([[0, 1], [1, 0], [1, 0]]),
    np.array([[0, 1], [1, 1], [1, 0]]),
    np.array([[1, 0], [0, 0], [1, 1]]),
    np.array([[1, 0], [1, 0], [1, 1]]),
    np.array([[0, 1], [1, 1], [0, 1]]),
    np.array([[1, 1], [0, 0], [1, 1]]),
    np.array([[1, 1], [0, 1], [1, 1]]),
    np.array([[0, 0], [1, 1], [1, 0]]),
    np.array([[1, 0], [0, 0], [0, 0]]),
    np.array([[1, 0], [1, 0], [0, 0]]),
    np.array([[1, 1], [0, 0], [0, 0]]),
    np.array([[1, 0], [0, 1], [0, 0]]),
    np.array([[1, 1], [0, 1], [0, 0]]),
    np.array([[1, 1], [0, 1], [1, 0]]),
    np.array([[1, 1], [0, 0], [1, 0]]),
    np.array([[0, 1], [0, 1], [0, 0]]),
    np.array([[0, 1], [0, 1], [1, 0]]),


]

# Enhance shadows of the image
enhanced_image = enhance_shadows(image)

# Convert the enhanced image to HSV color space
hsv_image = cv2.cvtColor(enhanced_image, cv2.COLOR_BGR2HSV)

# Extract the saturation channel
saturation_channel = hsv_image[:, :, 1]

# Define a saturation threshold for black and white conversion
saturation_threshold = 18

# Create a binary mask based on saturation
saturation_mask = (saturation_channel <= saturation_threshold).astype(np.uint8) * 255

# Apply the saturation mask to the original image
result_image = cv2.bitwise_and(enhanced_image, enhanced_image, mask=saturation_mask)

# Convert the result to grayscale
result_gray = cv2.cvtColor(result_image, cv2.COLOR_BGR2GRAY)

# Threshold the grayscale image to obtain a binary representation
_, binary_image = cv2.threshold(result_gray, 150, 255, cv2.THRESH_BINARY)

# Resize the image to a 3x2 matrix
resized_image = cv2.resize(binary_image, (2, 3))

# Invert the colors (assuming black dots on a white background)
resized_image = cv2.bitwise_not(resized_image)

# Convert the image matrix to a binary representation
matrix = (resized_image > 128).astype(int)

# Detect the Braille letter or number
braille_character, character_type = detect_braille_character(matrix)
print('Detected Braille Character:', braille_character)
print('Character Type:', character_type)


Detected Braille Character: F
Character Type: letter


In [ ]:
# Import the required libraries
from IPython.display import Audio
from gtts import gTTS

# Define the text you want to convert to speech
text = braille_character

# Choose the language of the speech (Hindi)
language = 'hi'

# Convert text to speech
myobj = gTTS(text=text, lang=language, slow=False)

# Save the audio file (optional)
myobj.save("speech.mp3")

# Play the audio directly in Colab
Audio("speech.mp3", autoplay=True)

code for sentence

In [ ]:
from google.colab.patches import cv2_imshow

def enhance_shadows(image):
    # Convert the image to LAB color space
    lab_image = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)

    # Split the LAB image into channels
    l_channel, a_channel, b_channel = cv2.split(lab_image)

    # Apply CLAHE to the L channel (lightness)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_l_channel = clahe.apply(l_channel)

    # Merge the enhanced L channel with the original A and B channels
    enhanced_lab_image = cv2.merge([enhanced_l_channel, a_channel, b_channel])

    # Convert the enhanced LAB image back to BGR color space
    enhanced_image = cv2.cvtColor(enhanced_lab_image, cv2.COLOR_LAB2BGR)

    return enhanced_image

def detect_braille_character(matrix):
    # Define the Braille alphabet mapping
    braille_alphabet = {
        (1, 0, 0, 0, 0, 0): 'A',
        (1, 0, 1, 0, 0, 0): 'B',
        (1, 1, 0, 0, 0, 0): 'C',
        (1, 1, 0, 1, 0, 0): 'D',
        (1, 0, 0, 1, 0, 0): 'E',
        (1, 1, 0, 1, 0, 0): 'F',
        (1, 1, 0, 1, 1, 0): 'G',
        (1, 1, 0, 0, 1, 0): 'H',
        (0, 1, 0, 1, 0, 0): 'I',
        (0, 1, 0, 1, 1, 0): 'J',
        (1, 0, 1, 0, 0, 0): 'K',
        (1, 1, 1, 0, 0, 0): 'L',
        (1 ,1 ,0 ,0 ,1 ,0): 'M',
        (1, 0, 1, 1, 1, 0): 'R',
        (1, 0, 1, 0, 1, 0): 'O',
        (1, 1, 1, 0, 1, 0): 'P',
        (1, 1, 1, 1, 1, 0): 'Q',
        (0, 1, 1, 1, 0, 0): 'S',
        (0, 1, 1, 1, 1, 0): 'T',
        (1, 0, 1, 0, 0, 1): 'U',
        (1, 0, 1, 0, 1, 1): 'V',
        (0, 1, 1, 1, 0, 1): 'W',
        (1, 1, 0, 0, 1, 1): 'X',
        (1, 1, 0, 1, 1, 1): 'Y',
        (1, 0, 0, 1, 1, 1): 'Z',
        # Add more mappings as needed
    }

    # Define the Braille number mapping
    braille_numbers = {
        (0, 0, 1, 1, 1, 0): '0',
        (1, 0, 0, 0, 0, 0): '1',
        (1, 0, 1, 0, 0, 0): '2',
        (1, 1, 0, 0, 0, 0): '3',
        (1, 0, 0, 1, 0, 0): '4',
        (1, 1, 0, 1, 0, 0): '5',
        (1, 1, 0, 1, 1, 0): '6',
        (1, 1, 0, 0, 1, 0): '7',
        (0, 1, 0, 1, 0, 0): '8',
        (0, 1, 0, 1, 1, 0): '9',
    }

    # Convert the matrix to a tuple of 1s and 0s
    dot_pattern = tuple(matrix.flatten().tolist())

    # Check if the dot pattern is in the Braille alphabet mapping
    if dot_pattern in braille_alphabet:
        return braille_alphabet[dot_pattern], 'letter'
    elif dot_pattern in braille_numbers:
        return braille_numbers[dot_pattern], 'number'
    else:
        return '?', 'unknown'

##############################################

def process_braille_image(image_path):
    # Load the image
    image = cv2.imread(image_path)

    # Preprocess the image
    enhanced_image = enhance_shadows(image)
    hsv_image = cv2.cvtColor(enhanced_image, cv2.COLOR_BGR2HSV)
    saturation_channel = hsv_image[:, :, 1]
    saturation_mask = (saturation_channel <= 18).astype(np.uint8) * 255
    result_image = cv2.bitwise_and(enhanced_image, enhanced_image, mask=saturation_mask)
    result_gray = cv2.cvtColor(result_image, cv2.COLOR_BGR2GRAY)
    _, binary_image = cv2.threshold(result_gray, 150, 255, cv2.THRESH_BINARY)

    # Segment individual characters
    characters = segment_braille_characters(binary_image)

    sentence = ""
    for character in characters:
        # Resize the character image to 3x2
        resized_character = cv2.resize(character, (2, 3))

        # Invert colors (assuming black dots on white background)
        resized_character = cv2.bitwise_not(resized_character)

        # Convert the image matrix to a binary representation
        matrix = (resized_character > 128).astype(int)

        # Detect the Braille letter or number
        braille_char, char_type = detect_braille_character(matrix)
        sentence += braille_char

    return sentence

def segment_braille_characters(binary_image):

   # Apply morphological operations (optional)
    kernel = np.ones((3, 3), np.uint8)  # Adjust kernel size as needed
    eroded_image = cv2.erode(binary_image, kernel, iterations=1)  # Reduce noise
    print(eroded_image)

    # Find contours
    contours, _ = cv2.findContours(eroded_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Filter contours based on area, aspect ratio, and solidity
    filtered_contours = []
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        aspect_ratio = float(w) / h
        solidity = cv2.contourArea(cnt) / cv2.contourArea(cv2.convexHull(cnt))  # Measure shape compactness
        if 15 < cv2.contourArea(cnt) < 100 and 0.7 < aspect_ratio < 1.3 and solidity > 0.8:  # Adjust thresholds as needed
            filtered_contours.append(cnt)

    # Extract ROI (Region of Interest) for each character
    segmented_characters = []
    for cnt in filtered_contours:
        x, y, w, h = cv2.boundingRect(cnt)
        roi = binary_image[y:y+h, x:x+w]
        segmented_characters.append(roi)

    return segmented_characters

# Example usage
image_path = '/content/love.png'  # Replace with the actual path
#image = cv2.imread(image_path)
sentence = process_braille_image(image_path)
print('Braille sentence:', sentence)



[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
Braille sentence: 


In [ ]:
def process_braille_image(image_path):
    # Load the image
    image = cv2.imread(image_path)

    # Preprocess the image
    enhanced_image = enhance_shadows(image)
    hsv_image = cv2.cvtColor(enhanced_image, cv2.COLOR_BGR2HSV)
    saturation_channel = hsv_image[:, :, 1]
    saturation_mask = (saturation_channel <= 18).astype(np.uint8) * 255
    result_image = cv2.bitwise_and(enhanced_image, enhanced_image, mask=saturation_mask)
    result_gray = cv2.cvtColor(result_image, cv2.COLOR_BGR2GRAY)
    _, binary_image = cv2.threshold(result_gray, 150, 255, cv2.THRESH_BINARY)

    # Segment individual characters
    characters = segment_braille_characters(binary_image)

    sentence = ""
    for character in characters:
        # Resize the character image to 3x2
        resized_character = cv2.resize(character, (2, 3))

        # Invert colors (assuming black dots on white background)
        resized_character = cv2.bitwise_not(resized_character)

        # Convert the image matrix to a binary representation
        matrix = (resized_character > 128).astype(int)

        # Detect the Braille letter or number
        braille_char, char_type = detect_braille_character(matrix)
        sentence += braille_char

    return sentence

def segment_braille_characters(binary_image):

    # Find contours
    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Filter contours based on area and aspect ratio
    filtered_contours = []
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        aspect_ratio = float(w) / h
        if 15 < cv2.contourArea(cnt) < 100 and 0.7 < aspect_ratio < 1.3:  # Adjust thresholds as needed
            filtered_contours.append(cnt)

    # Extract ROI (Region of Interest) for each character
    segmented_characters = []
    for cnt in filtered_contours:
        x, y, w, h = cv2.boundingRect(cnt)
        roi = binary_image[y:y+h, x:x+w]
        segmented_characters.append(roi)

    return segmented_characters

# Example usage
image_path = '/contents/ig.png'  # Replace with the actual path
sentence = process_braille_image(image_path)
print('Braille sentence:', sentence)


error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [ ]:
# Import the required libraries
from IPython.display import Audio
from gtts import gTTS

# Define the text you want to convert to speech
text = braille_character

# Choose the language of the speech (Hindi)
language = 'hi'

# Convert text to speech
myobj = gTTS(text=text, lang=language, slow=False)

# Save the audio file (optional)
myobj.save("speech.mp3")

# Play the audio directly in Colab
Audio("speech.mp3", autoplay=True)
